### ISSUE TITLE
🔌 [統合] エンタープライズツールとの連携が全く存在しない

### ISSUE THREAD

**Issue by susumutomita** [susumutomita/Paddi#79]
## 課題

Paddiは**完全に孤立したツール**です。企業は既に数十のツールを使用しており、新しいツールは既存のワークフローにシームレスに統合される必要がありますが、Paddiには一切の統合機能がありません。

## 企業の実際のツールスタック

```yaml
開発ツール:
  - Jira/Azure DevOps: タスク管理
  - GitHub/GitLab/Bitbucket: ソースコード管理
  - Jenkins/CircleCI/GitHub Actions: CI/CD
  - VS Code/IntelliJ: IDE

セキュリティツール:
  - Splunk/Datadog: SIEM
  - ServiceNow: ITSM
  - PagerDuty: インシデント管理
  - Slack/Teams: コミュニケーション

クラウド管理:
  - Terraform/Pulumi: IaC
  - AWS Control Tower/Azure Policy: ガバナンス
  - CloudHealth/Cloudability: コスト管理
```

## 競合の統合状況

| 統合先 | Qualys | Rapid7 | Tenable | Paddi |
|--------|--------|--------|---------|-------|
| Jira | ✅ 双方向同期 | ✅ | ✅ | ❌ |
| ServiceNow | ✅ 認定アプリ | ✅ | ✅ | ❌ |
| Slack | ✅ Bot + Workflow | ✅ | ✅ | ❌ |
| Splunk | ✅ ネイティブ | ✅ | ✅ | ❌ |
| Jenkins | ✅ プラグイン | ✅ | ✅ | ❌ |
| GitHub | ✅ Actions | ✅ | ✅ | ❌ |

## なぜこれが致命的か

- **ワークフロー分断**: 監査結果を手動でコピペする必要がある
- **自動化不可能**: CI/CDパイプラインに組み込めない
- **可視性の欠如**: 既存のダッシュボードで確認できない
- **重複作業**: チケット作成、通知、レポート作成が全て手動

### 1. Jira/ServiceNow 双方向統合

```python
class JiraIntegration:
    """Jiraとの双方向同期"""
    
    def __init__(self, jira_url: str, api_token: str):
        self.jira = JIRA(jira_url, token_auth=api_token)
        self.field_mapping = self._load_field_mapping()
    
    async def create_issue_from_finding(self, finding: SecurityFinding) -> str:
        """セキュリティFindingからJiraチケットを自動作成"""
        issue_dict = {
            'project': {'key': self.project_key},
            'summary': f"[Paddi] {finding.title}",
            'description': self._format_description(finding),
            'issuetype': {'name': 'Security Bug'},
            'priority': self._map_priority(finding.severity),
            'components': [{'name': 'Security'}],
            'customfield_10001': finding.finding_id,  # Paddi Finding ID
            'customfield_10002': finding.priority_score,
            'labels': ['paddi', f'severity-{finding.severity.lower()}']
        }
        
        issue = self.jira.create_issue(fields=issue_dict)
        
        # 双方向リンクを保存
        await self._store_issue_mapping(finding.finding_id, issue.key)
        
        # 添付ファイルを追加
        if finding.evidence:
            self.jira.add_attachment(issue, finding.evidence)
        
        return issue.key
    
    async def sync_status_updates(self):
        """Jiraのステータス変更をPaddiに反映"""
        async for event in self._watch_jira_webhooks():
            if event.type == 'issue_updated':
                await self._update_finding_status(event.issue_key, event.new_status)
```

### 2. Slack/Teams インテリジェントBot

```typescript
// Slack App with Block Kit UI
const PaddiSlackBot = {
  commands: {
    '/paddi scan': async (args) => {
      const modal = {
        type: 'modal',
        title: { type: 'plain_text', text: 'Security Scan' },
        blocks: [
          {
            type: 'input',
            element: {
              type: 'static_select',
              options: await getProjects(),
              placeholder: { type: 'plain_text', text: 'Select project' }
            }
          },
          {
            type: 'input',
            element: {
              type: 'checkboxes',
              options: [
                { text: 'IAM Analysis', value: 'iam' },
                { text: 'Network Security', value: 'network' },
                { text: 'Data Protection', value: 'data' }
              ]
            }
          }
        ]
      };
      await slack.views.open({ trigger_id, view: modal });
    },
    
    '/paddi status': async () => {
      const summary = await paddiAPI.getSecuritySummary();
      return {
        blocks: [
          {
            type: 'section',
            text: { type: 'mrkdwn', text: `*Security Score: ${summary.score}/100*` }
          },
          {
            type: 'section',
            fields: [
              { type: 'mrkdwn', text: `*Critical:* ${summary.critical}` },
              { type: 'mrkdwn', text: `*High:* ${summary.high}` }
            ]
          },
          {
            type: 'actions',
            elements: [
              {
                type: 'button',
                text: { type: 'plain_text', text: 'View Dashboard' },
                url: 'https://paddi.io/dashboard'
              }
            ]
          }
        ]
      };
    }
  },
  
  workflows: {
    // Slack Workflow Builder統合
    criticalFindingAlert: {
      trigger: 'paddi.critical_finding',
      steps: [
        { action: 'send_message', channel: '#security-alerts' },
        { action: 'create_jira_ticket' },
        { action: 'page_on_call', service: 'pagerduty' }
      ]
    }
  }
};
```

### 3. CI/CD ネイティブ統合

```yaml
# GitHub Actions
- name: Paddi Security Scan
  uses: paddi-security/scan-action@v1
  with:
    project-id: ${{ github.repository }}
    fail-on: critical
    create-issues: true
    
# Jenkins Pipeline
pipeline {
  stages {
    stage('Security Scan') {
      steps {
        paddiScan(
          credentialsId: 'paddi-api-key',
          projectId: env.PROJECT_NAME,
          threshold: [critical: 0, high: 5],
          publishReport: true
        )
      }
      post {
        always {
          publishHTML([
            reportDir: 'paddi-reports',
            reportFiles: 'security-report.html',
            reportName: 'Paddi Security Report'
          ])
        }
      }
    }
  }
}

# GitLab CI
paddi_scan:
  stage: security
  image: paddi/scanner:latest
  script:
    - paddi scan --format gitlab
  artifacts:
    reports:
      security: paddi-report.json
```

### 4. SIEM/Observability 統合

```python
class SplunkForwarder:
    """Splunk HECへのリアルタイム転送"""
    
    async def forward_findings(self, findings: List[SecurityFinding]):
        events = []
        for finding in findings:
            event = {
                "time": finding.detected_at.timestamp(),
                "source": "paddi",
                "sourcetype": "paddi:security:finding",
                "event": {
                    "severity": finding.severity,
                    "title": finding.title,
                    "resource": finding.resource_id,
                    "compliance": finding.compliance_mapping
                },
                "fields": {
                    "priority_score": finding.priority_score,
                    "environment": self.environment
                }
            }
            events.append(event)
        
        # Splunk HECに送信
        await self.hec_client.send_batch(events)
```

### 5. IDE統合

```typescript
// VS Code Extension
export function activate(context: vscode.ExtensionContext) {
  // インラインセキュリティ警告
  const diagnosticCollection = vscode.languages.createDiagnosticCollection('paddi');
  
  vscode.workspace.onDidSaveTextDocument(async (document) => {
    if (document.languageId === 'terraform') {
      const findings = await paddiAPI.scanFile(document.getText());
      
      const diagnostics = findings.map(finding => {
        const range = new vscode.Range(
          finding.line - 1, 0,
          finding.line - 1, Number.MAX_VALUE
        );
        
        const diagnostic = new vscode.Diagnostic(
          range,
          finding.message,
          finding.severity === 'CRITICAL' 
            ? vscode.DiagnosticSeverity.Error
            : vscode.DiagnosticSeverity.Warning
        );
        
        diagnostic.code = finding.rule_id;
        diagnostic.source = 'Paddi Security';
        return diagnostic;
      });
      
      diagnosticCollection.set(document.uri, diagnostics);
    }
  });
  
  // クイックフィックス
  vscode.languages.registerCodeActionProvider('terraform', {
    provideCodeActions(document, range, context) {
      const diagnostic = context.diagnostics[0];
      if (diagnostic?.source === 'Paddi Security') {
        const fix = new vscode.CodeAction(
          'Apply Paddi security fix',
          vscode.CodeActionKind.QuickFix
        );
        fix.edit = await paddiAPI.getQuickFix(diagnostic.code);
        return [fix];
      }
    }
  });
}
```

## 統合の優先順位

1. **Phase 1**: Slack/Teams通知（1週間）
2. **Phase 2**: Jira/GitHub Issues（2週間）
3. **Phase 3**: CI/CD統合（1ヶ月）
4. **Phase 4**: SIEM/Observability（2ヶ月）
5. **Phase 5**: IDE統合（3ヶ月）

## ROI

- **手動作業削減**: 80%（年間2000時間の節約）
- **MTTR短縮**: 60%（4時間→1.5時間）
- **開発者満足度**: NPS +40ポイント

## 結論

統合なしでは「また新しいツールが増えた」という不満しか生まず、採用されません。

ラベル: integration, ecosystem, priority-critical
